#GET //chama os registrados
GET http://localhost:8087/api/v1/avaliacao
Content-Type: application/json
###

#POST // inserir no banco
POST http://localhost:8087/api/v1/avaliacao
Content-Type: application/json

{
    "nota":"2",
    "idProduto":"1",
    "idRestaurante":"1",
    "idUsuario":"1"
}


###

#PUT // att
PUT http://localhost:8087/api/v1/avaliacao
Content-Type: application/json

{
    "id": 1,
    "nota":"3",
    "idProduto":"1",
    "idRestaurante":"1",
    "idUsuario":"1"
}

###

#DELETE //trocar o id no final
DELETE http://localhost:8087/api/v1/avaliacao/1
Content-Type: application/json